server:
  port: 8084
  
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/CircleServiceDB?verifyServerCertificate=false&useSSL=false&requireSSL=false
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: updates
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect